java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(project.java_version)
    }
}

group = project.maven_group
version = project.maven_version

base {
    archivesName = project.maven_name
}

repositories {
    mavenCentral()
}

jar {
    def projectName = project.name
    def licenseFile = rootProject.file("LICENSE")
    if (licenseFile.exists()) {
        from(licenseFile) {
            rename { "${it}_${projectName}" }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}
tasks.withType(Javadoc).configureEach {
    options {
        encoding = "UTF-8"
        addBooleanOption("Xdoclint:none", true)
        quiet()
    }
}
